### ISSUE TITLE
CTE expressions not working with select *

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingdb-ral#151]
run a query like

with did as ( select col1, col2 from table where col3 < 5 )
select * from did
And it returns extra rows and incorrect values

run 
with did as ( select col1, col2 from table where col3 < 5 )
select col1, col2 from did

And the correct results are output. There may be an issue with the relational algebra generator but more likely there is a bug that occurs when a project occurs immediately after a project when there are non operations on those projects.

**Comment by williamBlazing** [comment]
Is it possible to get more exact examples or description of the data or how the tables were created? I have not been able to replicate the issue

**Comment by felipeblazing** [comment]
It was done with Parquet. The file can't be shared.

**Comment by felipeblazing** [comment]
I will try and reproduce with dummy data

**Comment by aucahuasi** [comment]
Quick notice: just to let you know we are working on this one too, we will need to upgrade to cudf 0.10 and we are working on that +1

cc @rommelDB @Christian8491

**Comment by aucahuasi** [comment]
@felipeblazing @mlahir1 Fix is done, release is in coming! this will also help with other issues (e.g. #150 since all of this is over cudf 0.10 enhancements)

**Comment by aucahuasi** [comment]
@mlahir1 Please use explicit types for queries that contains timestamps/dates 

Example 1:
`with dateTemp as (select time_field, date_field from tb1 where time_field > TIMESTAMP '1960-05-05 12:34:55') select * from dateTemp
`
Example 2:
`select * from tb1 where time_field > TIMESTAMP '1960-05-05 12:34:55' AND date_field < DATE '1920-12-25'`
