### ISSUE TITLE
Can't select literal strings

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingdb-ral#152]
A query like

select 'some_value', col1 from table doesn't work

I would expect to be able to select literal strings to put into the output.

**Comment by aucahuasi** [comment]
Quick notice: just to let you know we are working on this one too +1

**Comment by aucahuasi** [comment]
@rommelDB +1

**Comment by aucahuasi** [comment]
Good news @mlahir1 @felipeblazing , we have a fix for this issue (thanks @rommelDB !) we will ship soon a new release based on cudf 0.10 where this should be working fine. We needed cudf 0.10 here too because cudf::fill has some issues in cudf 0.9 and that is the function we use for this feature.

**Comment by mlahir1** [comment]
Awesome, thanks for the update. looks like moving to cudf 0.10 is fixing lot of issues.
