### ISSUE TITLE
Connection to HDFS fails

### ISSUE THREAD

**Issue by aucahuasi** [BlazingDB/blazingdb-ral#198]
Env issues with libhdfs3

`Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 228, in hdfs
    return self.fs.hdfs(self.client, prefix, **kwargs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 54, in hdfs
    self._register_hdfs(client, prefix, root, fs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 133, in _register_hdfs
    'kerberosTicket': fs['kerberos_ticket']
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/bridge.py", line 31, in register_file_system
    return pyblazing.register_file_system(authority, type, root, params)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/api.py", line 1429, in register_file_system
    raise RuntimeError(ResponseErrorSchema.From(response.payload).errors)
RuntimeError: b'Cannot register the filesystem: HDFS connection failed'`

**Comment by Christian8491** [comment]
STEPS TO CONNECT HDFS

1. Create a folder <LIBHDFS3_HOME> wherever you want
2. cd LIBHDFS3_HOME
3. git clone https://github.com/Pivotal-DataFabric/attic-libhdfs3.git
4. mkdir build
5. cd build
6. Activate your environment: conda activate <ENV_NAME>
7. Ensure you have: (using:     conda list | grep libgsasl)
	libgsasl        1.8.0
9. Execute:
	../bootstrap --prefix=$CONDA_PREFIX
10. make
11. make install


------------------------------------------
NOTE: only if above doesn't work yet install these packages
Install these packages
	conda install -c anaconda boost
	conda install protobuf
	conda install -c anaconda krb5

@mlahir1
cc @rommelDB @aucahuasi

**Comment by mlahir1** [comment]
DO I have to set any JAVA_PATH, CLASSPATH in the env?
I have changed the JAVA_PATH which was pointing to CONDA_PREFIX to the place java is installed on the container.

**Comment by mlahir1** [comment]
it throws throws the following error after. installing the above packages.
```

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 228, in hdfs
    return self.fs.hdfs(self.client, prefix, **kwargs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 54, in hdfs
    self._register_hdfs(client, prefix, root, fs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 133, in _register_hdfs
    'kerberosTicket': fs['kerberos_ticket']
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/bridge.py", line 31, in register_file_system
    return pyblazing.register_file_system(authority, type, root, params)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/api.py", line 1429, in register_file_system
    raise RuntimeError(ResponseErrorSchema.From(response.payload).errors)
RuntimeError: b'Cannot register the filesystem: HDFS connection failed'
```

**Comment by Christian8491** [comment]
You should not set any JAVA_PATH.

Please, could you try with these two steps below:

- conda install -c conda-forge libgsasl  (from your <ENV_NAME>)

- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib


@mlahir1 let me know what happens with these commands, please. cc @rommelDB @aucahuasi

**Comment by mlahir1** [comment]
@Christian8491, I am still facing the same error,

cc: @rommelDB  @aucahuasi

**Comment by Christian8491** [comment]
Hi @mlahir1 could you please send us the ouput for these commands:
```
conda list | grep sasl
conda list | grep proto*
ldd $CONDA_PREFIX/lib/libhdfs3.so
```
cc @aucahuasi @rommelDB

**Comment by mlahir1** [comment]
```
(bzsqlenv) root@07026f0ad6c4:~# conda list | grep sasl
libgsasl                  1.8.0             h19a2143_1004    conda-forge
(bzsqlenv) root@07026f0ad6c4:~# conda list | grep proto*
blazingdb-protocol        1.0                      pypi_0    pypi
libprotobuf               3.8.0                h8b12597_0    conda-forge
protobuf                  3.8.0            py37he6710b0_0  
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-recordproto          1.14.2            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge

(bzsqlenv) root@07026f0ad6c4:~# ldd $CONDA_PREFIX/lib/libhdfs3.so
        linux-vdso.so.1 =>  (0x00007ffca0bd5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ab97f5000)
        libuuid.so.1 => /conda/envs/rapids/lib/libuuid.so.1 (0x00007f5aba126000)
        libprotobuf.so.19 => /conda/envs/rapids/lib/libprotobuf.so.19 (0x00007f5ab9558000)
        libxml2.so.2 => /conda/envs/rapids/lib/libxml2.so.2 (0x00007f5ab9fbb000)
        libkrb5.so.3 => /conda/envs/rapids/lib/libkrb5.so.3 (0x00007f5ab947c000)
        libgsasl.so.7 => /conda/envs/bzsqlenv/lib/libgsasl.so.7 (0x00007f5ab9f9b000)
        libstdc++.so.6 => /conda/envs/rapids/lib/libstdc++.so.6 (0x00007f5ab9308000)
        libgcc_s.so.1 => /conda/envs/rapids/lib/libgcc_s.so.1 (0x00007f5ab9f86000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ab8f3e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5ab9f13000)
        libz.so.1 => /conda/envs/rapids/lib/./libz.so.1 (0x00007f5ab9f6b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5ab8d3a000)
        libicuuc.so.64 => /conda/envs/rapids/lib/./libicuuc.so.64 (0x00007f5ab8b63000)
        liblzma.so.5 => /conda/envs/rapids/lib/./liblzma.so.5 (0x00007f5ab9f41000)
        libiconv.so.2 => /conda/envs/rapids/lib/./libiconv.so.2 (0x00007f5ab8a7b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ab8772000)
        libk5crypto.so.3 => /conda/envs/rapids/lib/./libk5crypto.so.3 (0x00007f5ab8753000)
        libcom_err.so.3 => /conda/envs/rapids/lib/./libcom_err.so.3 (0x00007f5ab9f3a000)
        libkrb5support.so.0 => /conda/envs/rapids/lib/./libkrb5support.so.0 (0x00007f5ab8744000)
        libcrypto.so.1.1 => /conda/envs/rapids/lib/./libcrypto.so.1.1 (0x00007f5ab847a000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5ab825f000)
        libntlm.so.0 => /conda/envs/bzsqlenv/lib/./libntlm.so.0 (0x00007f5ab8254000)
        libgssapi_krb5.so.2 => /conda/envs/bzsqlenv/lib/./libgssapi_krb5.so.2 (0x00007f5ab8204000)
        libicudata.so.64 => /conda/envs/rapids/lib/././libicudata.so.64 (0x00007f5ab67c0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5ab65b7000)

```
cc @aucahuasi @rommelDB

**Comment by aucahuasi** [comment]
Thanks @mlahir1 please send us how you are registering the HDFS file system (the python snippet) Do you have a kerberos instance there? If not, then it should be something like this:

`bc.hdfs('hdfsdiskA', host='35.185.45.244', port=54310, user='hadoop')`

where host:port must point to the HDFS server node with the valid user there (e.g. hadoop)
After that, it should be possible to create any table, for example:

```
files = 'hdfs://hdfsdiskA/root_folder/data/customer_parquet/*.parquet'
t = bc.create_table('customer', files)
print(t)
```

**Comment by mlahir1** [comment]
I have kerborized the instance and then I am running the following code.
```
bc.hdfs('dir', 
        host='Name node', 
        port=8020, 
        user='l0m02dy',
        kerb_ticket="/tmp/krb5cc_0")
```

to connect to hdfs.

**Comment by aucahuasi** [comment]
Great @mlahir1 If you have a kerberos instance you should use _kerberos_ticket_ instead, something like this:

```
bc.hdfs('dir', 
        host='IP_NAME_NODE', 
        port=8020, 
        user='l0m02dy',
        kerberos_ticket="/tmp/krb5cc_0")
```

Also please note the host argument must be a host or IP

**Comment by mlahir1** [comment]
@aucahuasi, I am still getting the same error when I replace `kerberos_ticket`.

```
>>> bc.hdfs('<dir path>', 
...         host='<name node>', 
...         port=8020, 
...         user='l0m02dy',
...         kerberos_ticket="/tmp/krb5cc_0")
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 228, in hdfs
    return self.fs.hdfs(self.client, prefix, **kwargs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 54, in hdfs
    self._register_hdfs(client, prefix, root, fs)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/filesystem.py", line 133, in _register_hdfs
    'kerberosTicket': fs['kerberos_ticket']
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/bridge.py", line 31, in register_file_system
    return pyblazing.register_file_system(authority, type, root, params)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/api.py", line 1429, in register_file_system
    raise RuntimeError(ResponseErrorSchema.From(response.payload).errors)
RuntimeError: b'Cannot register the filesystem: HDFS connection failed'
```

I using the IP of the Name Node itself.

**Comment by aucahuasi** [comment]
Hi @mlahir1 just to let you know we keep testing this issue with our kerberos/hdfs instances, we will get back to you as soon as we have some news +1 cc @rommelDB @gcca

**Comment by aucahuasi** [comment]
Hi @mlahir1 we have the fixes in these branches:

https://github.com/BlazingDB/blazingdb-io/tree/bugfix/libhdfs-native
https://github.com/BlazingDB/pyBlazing/tree/bugfix/libhdfs-native

Also there are some technical aspects you need to know for your hdfs and kerberos instances:

Environment Instructions:
Make sure doesn't exists another hdfs lib on the conda env:
ls $CONDA_ENV/lib/libhdfs*
On the environment where the blazing-engine was started set the environment variables below:

HADOOP_HOME: the root of your installed Hadoop distribution.

JAVA_HOME: the location of your Java SDK installation.

ARROW_LIBHDFS_DIR (optional): explicit location of libhdfs.so if it is installed somewhere other than $HADOOP_HOME/lib/native.

CLASSPATH: must contain the Hadoop jars. You can set these using: export CLASSPATH=$HADOOP_HOME/bin/hdfs classpath --glob

More docs here:  https://arrow.apache.org/docs/python/filesystems.html

cc @rommelDB @gcca

**Comment by mlahir1** [comment]
Hello @aucahuasi 

I have all the below env variables set. But these are used for connecting via pyarrow instead of libhdfs3 library.

I will verify these changes and let you know what happens.

@gcca @rommelDB

**Comment by aucahuasi** [comment]
@mlahir1 yep you need to use those branches for now, we'll merge those into develop this week once we have implemented automatic tests with kerberos and hdfs into our end-to-end testing framework ;) cc @Christian8491 @kharoc

**Comment by mlahir1** [comment]
@aucahuasi 

using the fixes in these branches. I am able to connect using hdfs. 

Now I get following error when i try to create a table.
```
>>>bc.create_table('svs', 'hdfs://svs_ec/000000_0', file_format='orc')
or
>>>bc.create_table('svs', 'hdfs://<name_node>/<full absolute path>/svs_ec/000000_0', file_format='orc')

>>>bc.create_table('svs', 'hdfs://user/hive/warehouse/wm_gpulab.db/svs_ec/000000_0',  file_format='orc')
b"In function ddlCreateTableService: cannot create the table: Path 'hdfs://user/hive/warehouse/wm_gpulab.db/svs_ec/000000_0' does not exist. File paths are expected to be in one of the following formats:   For local file paths: '/folder0/folder1/fileName.extension'    For s3 file paths: 's3://registeredFileSystemName/folder0/folder1/fileName.extension'    For HDFS file paths: 'hdfs://registeredFileSystemName/folder0/folder1/fileName.extension'"
```

cc @gcca @rommelDB

**Comment by aucahuasi** [comment]
Hi @mlahir1 could you please modify your script for each create table

```
t = bc.create_table('svs', 'hdfs://svs_ec/000000_0', file_format='orc')
print(t)
```

Additionally you can check if the table was ok with 
```
if t.is_valid():
    foo()
```

I see some tables were created, for example 

`bc.create_table('svs', 'hdfs://svs_ec/000000_0', file_format='orc')`

So it seems the issue is with the file hdfs://user/hive/warehouse/wm_gpulab.db/svs_ec/000000_0 right?

**Comment by mlahir1** [comment]
@aucahuasi 

None of the create table, creates tables. I just added the other two, to show they also won't work and give the same error.
```
>>>bc.create_table('svs', 'hdfs://svs_ec/000000_0', file_format='orc')
or
>>>bc.create_table('svs', 'hdfs://<name_node>/<full absolute path>/svs_ec/000000_0', file_format='orc')
```

**Comment by aucahuasi** [comment]
I see, going to debug the create table then, it seems register files system is fine. Let us check this one, we are close ;)

+ @Christian8491

**Comment by aucahuasi** [comment]
Hi @mlahir1 just to comment, we are close to solve the issue, the most challenging part here was to have a kerberized hadoop where to perform the testing.

**Comment by aucahuasi** [comment]
Hi @mlahir1 we have been able to replicate the issue and fix it the create table and run query on Kerberized HDFS instances! The PRs are:

https://github.com/BlazingDB/blazingdb-io/pull/23
https://github.com/BlazingDB/pyBlazing/pull/114

Is just a matter of time to merge those into develop, but you can give it a shot, for that please use these branches:

blazingdb_protocol_branch=develop
blazingdb_io_branch=bugfix/libhdfs-native
blazingdb_communication_branch=develop
blazingdb_ral_branch=develop
blazingdb_orchestrator_branch=develop
blazingdb_calcite_branch=develop
pyblazing_branch=bugfix/libhdfs-native

Also on the environment (or in the shell where you run manually blazing-engine) set these envs:
- HADOOP_HOME: the root of your installed Hadoop distribution. Download from here the most compatible Hadoop version https://archive.apache.org/dist/hadoop/core/
- JAVA_HOME: the location of your Java SDK installation (this one should point to CONDA_PREFIX)
- ARROW_LIBHDFS_DIR: explicit location of libhdfs.so if it is installed somewhere other than $HADOOP_HOME/lib/native.
- CLASSPATH: must contain the Hadoop jars. You can set these using: export CLASSPATH=$HADOOP_HOME/bin/hdfs classpath --glob

Also, make sure:
1. You have Kerberos credentials with kinit in you host
2. Have the /etc/krb5.conf file in your host
3. You can ping your Kerberos and HDFS hosts (check your /etc/hosts)
4. In $HADOOP_HOME/etc/hadoop/ you need to have correctly configured (same as your HDFS server) these files:
- core-site.xml
- hdfs-site.xml
- mapred-site.xml
- ssl-client.xml
- ssl-server.xml
- yarn-site.xml

Here a demo code:

```
from blazingsql import BlazingContext

BlazingContext(connection = 'localhost:8889', dask_client = None, run_orchestrator=False, run_engine=False, run_algebra=False, network_interface='wlp2s0', leave_processes_running=True)

result, error_msg, fs = bc.hdfs('cluster1',host='172.22.0.3',port=9000,user='jhs',kerberos_ticket="/home/percy/krb5cc_0")

print(result)
print(error_msg)
print(fs)

t = bc.create_table('nation', 'hdfs://cluster1/tmp/nation_0_0.parquet')
print(t)

if t.is_valid():
    result = bc.sql("select * from nation").get()
    print(result.columns)


```

**Comment by aucahuasi** [comment]
Hi @mlahir1 we have been able to replicate the issue and fix it the create table and run query on Kerberized HDFS instances! The PRs are:

https://github.com/BlazingDB/blazingdb-io/pull/23
https://github.com/BlazingDB/pyBlazing/pull/114

Is just a matter of time to merge those into develop, but you can give it a shot, for that please use these branches:

blazingdb_protocol_branch=develop
blazingdb_io_branch=bugfix/libhdfs-native
blazingdb_communication_branch=develop
blazingdb_ral_branch=develop
blazingdb_orchestrator_branch=develop
blazingdb_calcite_branch=develop
pyblazing_branch=bugfix/libhdfs-native

Also on the environment (or in the shell where you run manually blazing-engine) set these envs:
- HADOOP_HOME: the root of your installed Hadoop distribution. Download from here the most compatible Hadoop version https://archive.apache.org/dist/hadoop/core/
- JAVA_HOME: the location of your Java SDK installation (this one should point to CONDA_PREFIX)
- ARROW_LIBHDFS_DIR: explicit location of libhdfs.so if it is installed somewhere other than $HADOOP_HOME/lib/native.
- CLASSPATH: must contain the Hadoop jars. You can set these using: export CLASSPATH=$HADOOP_HOME/bin/hdfs classpath --glob

Also, make sure:
1. You have Kerberos credentials with kinit in you host
2. Have the /etc/krb5.conf file in your host
3. You can ping your Kerberos and HDFS hosts (check your /etc/hosts)
4. In $HADOOP_HOME/etc/hadoop/ you need to have correctly configured (same as your HDFS server) these files:
- core-site.xml
- hdfs-site.xml
- mapred-site.xml
- ssl-client.xml
- ssl-server.xml
- yarn-site.xml

Here a demo code:

```
from blazingsql import BlazingContext

BlazingContext(connection = 'localhost:8889', dask_client = None, run_orchestrator=False, run_engine=False, run_algebra=False, network_interface='wlp2s0', leave_processes_running=True)

result, error_msg, fs = bc.hdfs('cluster1',host='172.22.0.3',port=9000,user='jhs',kerberos_ticket="/home/percy/krb5cc_0")

print(result)
print(error_msg)
print(fs)

t = bc.create_table('nation', 'hdfs://cluster1/tmp/nation_0_0.parquet')
print(t)

if t.is_valid():
    result = bc.sql("select * from nation").get()
    print(result.columns)
```

Please let us know! btw Thanks @Christian8491 @rommelDB

**Comment by mlahir1** [comment]
@aucahuasi do you know when these fixes will merge into develop branch? if it take sometime, I will go ahead and verify with the branches you have mentioned.

**Comment by aucahuasi** [comment]
@mlahir1 Maybe tomorrow or Wednesday, I would suggest to use those branches directly

**Comment by aucahuasi** [comment]
Hi @mlahir1 the PRs were merged into develop so all the fixes are there, please feel free to give it a try! cc @felipeblazing @Christian8491 @rommelDB

**Comment by mlahir1** [comment]
Works. I have tested and and I am able to read fine from HDFS from a kerborized container.

**Comment by aucahuasi** [comment]
Great news @mlahir1! Thanks @rommelDB @Christian8491 @gcca !
