### ISSUE TITLE
support for NULL as a literal

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingdb-ral#200]
The following line of sql
```CASE WHEN a = 0 THEN b ELSE NULL END a,```

throws this error:
```In get_output_type_expression function: unsupported operator token, null:INTEGER
In get_output_type_expression function: unsupported operator token, null:INTEGER
>>> res_gdf = result.columns```

**Comment by aucahuasi** [comment]
Thanks @mlahir1 cc @rommelDB @Christian8491

**Comment by aucahuasi** [comment]
@mlahir1 We support that operation but it seems we have a bug there in the parser (with that token 
 :INTEGER), tomorrow we will work on the fix +1 cc @jeanp413

**Comment by mlahir1** [comment]
verified. works! Thanks
