### ISSUE TITLE
Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingdb-ral#201]
the following query gives the following error:
```

bc = BlazingContext(logs_destination = 'logs')
>>> bc.create_table('sv', get_files('/data', 'wm_gpulab', 'sv_ec', '*'), file_format='orc')
>>> query = '''
... WITH 
... cal AS (
...     SELECT _col0 AS date_c,
...            _col1 AS date_l,
...            _col2 AS date_r
...     FROM dates
... ),
... 
... cal_c AS (SELECT date_c AS dt FROM cal),
... 
... 
... store_visit_c AS (
...     SELECT
...         _col15 , CAST(_col55 AS DATE) AS dt,_col13
...     FROM
...         sv,
...         cal_c AS cal_c
...     WHERE
...         _col2 = 'US'
...         AND CAST(_col55 AS DATE) = cal_c.dt
... )
... SELECT * FROM store_visit_c
... '''
>>> result = bc.sql(query).get()
Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str
Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str
```

[logs.tar.gz](https://github.com/BlazingDB/blazingdb-ral/files/3757668/logs.tar.gz)

**Comment by williamBlazing** [comment]
@mlahir1 The error we are seeing in the logs is an allocation error. Out of curiosity, approximately how many rows would you expect to be in all the files you are loading?
Also, can you confirm you can run any other queries in this environment?

**Comment by mlahir1** [comment]
@williamBlazing 
yes, i can run other queries in this environment.
length of store_visit is 
```
>>> sv = cudf.read_orc(get_files('/data', 'wm_gpulab', 'sv_ec', '*')[0], use_index=False)
>>> len(sv)
1059149
```
and cal_c is
```
          dt
0 2019-08-05
1 2019-08-12
2 2019-08-11
3 2019-08-08
4 2019-08-07
5 2019-08-10
6 2019-08-06
7 2019-08-09
```

there should no problem at all for fitting these data in the memory.

**Comment by aucahuasi** [comment]
Hi @mlahir1 could you please tell us what are the types for these columns
_col1
_col2
_col55

We are assuming _col55 is str but it would help to know the exact type ;)

cc @Christian8491 @williamBlazing

**Comment by Christian8491** [comment]
@mlahir1 to let you know we are working on this problem. As soon as we will have answers for that we let you know. cc @aucahuasi  @williamBlazing .

**Comment by aucahuasi** [comment]
@mlahir1 The fix is already merged, let's know how it gows please ;) thanks @Christian8491

**Comment by mlahir1** [comment]
@aucahuasi This is fixed. Thanks!
