### ISSUE TITLE
Error on the communication between Orchestrator and Calcite: Improperly Formatted Query

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingdb-ral#219]
```
... WITH
... scans_lr as ( ... ) -> gives expected results
... store_visit_lr as ( ... ) -> gives expected results
... visit_scans_lr AS (
...     SELECT 
...         a.visit_dt AS visit_dt
...     FROM
...         scans_lr AS a INNER JOIN store_visit_lr AS b
...             ON a.store_nbr = b.store_nbr
... )
... 
... SELECT * FROM visit_scans_lr
... '''
>>> result = bc.sql(query).get()

```
is giving me the following error:
```
Error on the communication between Orchestrator and Calcite: Improperly Formatted Query
org.apache.calcite.sql2rel.ReflectiveConvertletTable.lambda$registerNodeTypeMethod$0(ReflectiveConvertletTable.java:86)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/sql.py", line 62, in get
    temp = internal_api.run_query_get_results(self.client, self.metaToken, self.startTime)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/apiv2/bridge.py", line 43, in run_query_get_results
    return pyblazing.run_query_get_results(metaToken, startTime)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/api.py", line 1026, in run_query_get_results
    return _run_query_get_results(metaToken, startTime)
  File "/conda/envs/bzsqlenv/lib/python3.7/site-packages/pyblazing/api.py", line 1037, in _run_query_get_results
    for result in distMetaToken:
TypeError: 'NoneType' object is not iterable
```

**Comment by aucahuasi** [comment]
Thanks @mlahir1 cc @Christian8491

**Comment by aucahuasi** [comment]
+ @rommelDB

**Comment by aucahuasi** [comment]
@jeanp413 +1

**Comment by aucahuasi** [comment]
Hi @mlahir1 we have been testing the same query but with TPCH tables and were unable to reproduce the issue. Could you please give us more details (column types, full calcite, ral, orchestrator logs)?

```
bc.create_table('customer', "/tpch/customer_*.orc")
bc.create_table('orders', "/tpch/orders_*.orc")

WITH
    visit_scans_lr AS (
        SELECT 
            b.o_orderdate AS visit_dt
        FROM
            customer AS a INNER JOIN orders AS b
                ON a.c_custkey = b.o_custkey
    )
SELECT * FROM visit_scans_lr
```
cc @jeanp413 @rommelDB @Christian8491

**Comment by mlahir1** [comment]
@aucahuasi can you let me know how to get these logs. So i can give them to you.

**Comment by aucahuasi** [comment]
Sure @williamBlazing will share with you how to do that cc @jeanp413

**Comment by williamBlazing** [comment]
@mlahir1 do you launch the BlazingSQL services manually or do you have BlazingContext launch them for you? if you use have BlazingContext launch the services for you, you can provide it the following parameter:
`bc = BlazingContext(logs_destination='folder_name')`
and it will place the logs at `$CONDA_PREFIX/folder_name`
If will create a file for the stdout and stderr for each of the three services: blazingsql-engine, blazingsql-orchestrator and blazingsql-algebra

If instead you launch the BlazingSQL services yourself, in which case you do something like this:
`bc = BlazingContext(run_algebra=False, run_engine=False, run_orchestrator=False)`, then the logs would just the be stdout and stderr produced by the services.

**Comment by Christian8491** [comment]
@mlahir1 please, could you give information of the dtype  from `a.store_nbr` and  `b.store_nbr` ? Thanks!

**Comment by mlahir1** [comment]
@Christian8491 the dtype is int32 for both.

**Comment by Christian8491** [comment]
Thanks @mlahir1 !
